
workflows:
  build-eierhuette:
    name: Build Eierhütte Cordova App
    max_build_duration: 20
    environment:
      node: 16
      java: 11
    scripts:
      - npm install -g cordova
      - cordova platform add android
      - cordova build android
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
