workflows:
  build-eierhuette:
    name: Build Eierhütte Cordova App
    max_build_duration: 20
    environment:
      node: 16
      java: 11
    scripts:
      - npm install -g cordova
      - cordova platform add android
      # ↓ Gradle-Version manuell setzen (vor dem Build!)
      - sed -i.bak 's/distributionUrl=.*/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.0-all.zip/' platforms/android/gradle/wrapper/gradle-wrapper.properties
      # ↓ Jetzt erst bauen
      - cordova build android
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
