workflows:
  build-eierhuette:
    name: Build Eierhütte Cordova App
    max_build_duration: 20
    environment:
      node: 16
      java: 11
    scripts:
      - npm install -g cordova
      - cordova platform add android
      # ↓ Gradle auf kompatible Version setzen
      - cd platforms/android && ./gradlew wrapper --gradle-version 8.0 && cd ../..
      # ↓ Jetzt den eigentlichen Build starten
      - cordova build android
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
