workflows:
  build-eierhuette:
    name: Build Eierhütte Cordova App
    max_build_duration: 20
    environment:
      node: 16
      java: 17   # ← Wichtig!
    scripts:
      - npm install -g cordova
      - cordova plugin add cordova-plugin-geolocation
      - cordova plugin add cordova.plugins.diagnostic
      - cordova platform add android
      # Initialer Build nur zur Gradle-Dateierstellung (Fehler erlaubt)
      - |
        cordova build android || echo "Initial build failed, continuing to patch Gradle..."
      # Jetzt ist gradle-wrapper.properties vorhanden → Gradle-Version setzen
      - sed -i.bak 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip|' platforms/android/gradle/wrapper/gradle-wrapper.properties
      # Finaler Build
      - cordova build android
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
